# Generated by Django 3.2 on 2022-06-10 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awwards', '0003_auto_20220610_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='pub_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_images',
            new_name='project_photo',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='content',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='design',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='usability',
        ),
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='projects',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwards.profile'),
        ),
    ]
