# Generated by Django 3.2 on 2022-06-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_projects_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='contact',
        ),
    ]
