# Generated by Django 3.2 on 2022-06-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_rename_phone_number_profile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
