# Generated by Django 3.2 on 2022-06-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0008_auto_20220611_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='creativity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
    ]
